-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 13:41:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`support_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`support_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `outcome_contribution` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`support_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`support_staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `support_role_id` INT NOT NULL,
  `effectiveness` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_support_staff_support_roles_idx` (`support_role_id` ASC) VISIBLE,
  UNIQUE INDEX `person_id_support_role_id_UNIQUE` (`person_id` ASC, `support_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_support_staff_people`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_support_staff_support_roles`
    FOREIGN KEY (`support_role_id`)
    REFERENCES `mydb`.`support_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '- one couch can have multiple teams - use many to many';


-- -----------------------------------------------------
-- Table `mydb`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clubs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `home_city_id` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `closure_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clubs_cities_idx` (`home_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_clubs_cities`
    FOREIGN KEY (`home_city_id`)
    REFERENCES `mydb`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `club_id` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `closure_date` DATE NULL,
  `league_id` INT NULL,
  `league_position` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_clubs1_idx` (`club_id` ASC) VISIBLE,
  UNIQUE INDEX `league_id_league_position_UNIQUE` (`league_id` ASC, `league_position` ASC) VISIBLE,
  CONSTRAINT `fk_teams_clubs1`
    FOREIGN KEY (`club_id`)
    REFERENCES `mydb`.`clubs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `preffered_position_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_people_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_players_positions_idx` (`preffered_position_id` ASC) VISIBLE,
  INDEX `fk_players_teams_idx` (`team_id` ASC) VISIBLE,
  UNIQUE INDEX `person_id_UNIQUE` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_people`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_players_positions`
    FOREIGN KEY (`preffered_position_id`)
    REFERENCES `mydb`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_players_teams`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leagues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stadiums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `club_id` INT NULL,
  `city_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stadiums_clubs_idx` (`club_id` ASC) VISIBLE,
  INDEX `fk_stadiums_cities_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_stadiums_clubs`
    FOREIGN KEY (`club_id`)
    REFERENCES `mydb`.`clubs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stadiums_cities`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stadium_id` INT NULL,
  `time` DATETIME NOT NULL,
  `duration` TIME NOT NULL,
  `first_half_duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_stadiums_idx` (`stadium_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_stadiums`
    FOREIGN KEY (`stadium_id`)
    REFERENCES `mydb`.`stadiums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players_performances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players_performances` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  `game_id` BIGINT NOT NULL,
  `team_id` INT NOT NULL,
  `defensive_performance` DOUBLE NOT NULL,
  `offensive_performance` DOUBLE NOT NULL,
  `cooperative_performance` DOUBLE NOT NULL,
  `performance_start` TIME NOT NULL COMMENT 'game time that the performance started\n',
  `performance_end` TIME NOT NULL COMMENT 'game time that performance ended',
  PRIMARY KEY (`id`),
  INDEX `fk_players_performances_players_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_players_performances_positions_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_players_performances_events_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_players_performances_teams_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_performances_players`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_players_performances_positions`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_players_performances_games`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_players_performances_teams`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Measure of player performance during event';


-- -----------------------------------------------------
-- Table `mydb`.`penalties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`penalties` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_performance_id` BIGINT NOT NULL,
  `type` ENUM('YELLOW', 'RED') NOT NULL,
  `game_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_penalties_players_performances_idx` (`player_performance_id` ASC) VISIBLE,
  CONSTRAINT `fk_penalties_players_performances`
    FOREIGN KEY (`player_performance_id`)
    REFERENCES `mydb`.`players_performances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shoot_outcomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shoot_outcomes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`penalty_shots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`penalty_shots` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `goalkeeper_performance_id` BIGINT NOT NULL,
  `shooter_performance_id` BIGINT NOT NULL,
  `outcome_id` INT NOT NULL,
  `game_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_penalty_shots_shoot_outcome_idx` (`outcome_id` ASC) VISIBLE,
  INDEX `fk_penalty_shots_players_performances_goalkeeper_idx` (`goalkeeper_performance_id` ASC) VISIBLE,
  INDEX `fk_penalty_shots_players_performance_shooter_idx` (`shooter_performance_id` ASC) VISIBLE,
  CONSTRAINT `fk_penalty_shots_players_performances_goalkeeper`
    FOREIGN KEY (`goalkeeper_performance_id`)
    REFERENCES `mydb`.`players_performances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_penalty_shots_players_performance_shooter`
    FOREIGN KEY (`shooter_performance_id`)
    REFERENCES `mydb`.`players_performances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_penalty_shots_shoot_outcome`
    FOREIGN KEY (`outcome_id`)
    REFERENCES `mydb`.`shoot_outcomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goal_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goal_attempts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `game_time` TIME NOT NULL,
  `defender_performance_id` BIGINT NOT NULL,
  `attacker_performance_id` BIGINT NOT NULL,
  `outcome_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goal_attempts_shoot_outcomes_idx` (`outcome_id` ASC) VISIBLE,
  INDEX `fk_goal_attempts_players_performances_defender_idx` (`defender_performance_id` ASC) VISIBLE,
  INDEX `fk_goal_attempts_players_performances_attacker_idx` (`attacker_performance_id` ASC) VISIBLE,
  CONSTRAINT `fk_goal_attempts_players_performances_defender`
    FOREIGN KEY (`defender_performance_id`)
    REFERENCES `mydb`.`players_performances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_goal_attempts_players_performances_attacker`
    FOREIGN KEY (`attacker_performance_id`)
    REFERENCES `mydb`.`players_performances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_goal_attempts_shoot_outcomes`
    FOREIGN KEY (`outcome_id`)
    REFERENCES `mydb`.`shoot_outcomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`injuries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`injuries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `impact_time_days` INT NOT NULL,
  `seriousness` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_injuries_players_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_injuries_players`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`support_staff_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`support_staff_teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `support_staff_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `job_start` DATE NOT NULL,
  `job_end` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `support_staff_id_team_id_job_start_UNIQUE` (`support_staff_id` ASC, `team_id` ASC, `job_start` ASC) VISIBLE,
  CONSTRAINT `fk_support_staff_teams_support_staff`
    FOREIGN KEY (`support_staff_id`)
    REFERENCES `mydb`.`support_staff` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_support_staff_teams_teams`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
